application: tv-stalker
version: 3
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico

- url: /oauth/signin_twitter
  script: oauth_login.py

- url: /oauth/twitter
  script: oauth_login.py

- url: /oauth/signout
  script: oauth_login.py

- url: /oauth/cleanup_sessions
  script: oauth_login.py

- url: /rpc
  script: rpc.py

- url: /.*
  script: tvstalker.py
